title: Tessa Eagle
description: Graduate Student Researcher
site_title: 'Tessa Eagle'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: tessaeagle
blog_url: 
email: teagle@ucsc.edu
keybase_username: 
twitter_username: tessuheagle
reddit_username: 

# absolute or relative
profile_picture: assets/images/prof2.jpg

# Google Analytics ID
google_analytics: UA-152311203-1
